export const states = [
  { value: "andhra-pradesh", label: "Andhra Pradesh" },
  { value: "arunachal-pradesh", label: "Arunachal Pradesh" },
  { value: "assam", label: "Assam" },
  { value: "bihar", label: "Bihar" },
  { value: "chhattisgarh", label: "Chhattisgarh" },
  { value: "delhi", label: "Delhi" },
  { value: "goa", label: "Goa" },
  { value: "gujarat", label: "Gujarat" },
  { value: "haryana", label: "Haryana" },
  { value: "himachal-pradesh", label: "Himachal Pradesh" },
  { value: "jharkhand", label: "Jharkhand" },
  { value: "karnataka", label: "Karnataka" },
  { value: "kerala", label: "Kerala" },
  { value: "ladakh", label: "Ladakh" },
  { value: "maharashtra", label: "Maharashtra" },
  { value: "manipur", label: "Manipur" },
  { value: "meghalaya", label: "Meghalaya" },
  { value: "mizoram", label: "Mizoram" },
  { value: "nagaland", label: "Nagaland" },
  { value: "odisha", label: "Odisha" },
  { value: "punjab", label: "Punjab" },
  { value: "rajasthan", label: "Rajasthan" },
  { value: "sikkim", label: "Sikkim" },
  { value: "tamil-nadu", label: "Tamil Nadu" },
  { value: "telangana", label: "Telangana" },
  { value: "tripura", label: "Tripura" },
  { value: "uttar-pradesh", label: "Uttar Pradesh" },
  { value: "uttarakhand", label: "Uttarakhand" },
  { value: "west-bengal", label: "West Bengal" },
  { value: "puducherry", label: "Puducherry" },
];

export const citiesByState = {
  "andhra-pradesh": [
    { value: "visakhapatnam", label: "Visakhapatnam" },
    { value: "vijayawada", label: "Vijayawada" },
    { value: "guntur", label: "Guntur" },
    { value: "tirupati", label: "Tirupati" },
    { value: "nellore", label: "Nellore" },
    { value: "kadapa", label: "Kadapa" },
    { value: "chittoor", label: "Chittoor" },
  ],
  "arunachal-pradesh": [
    { value: "itanagar", label: "Itanagar" },
    { value: "naharlagun", label: "Naharlagun" },
    { value: "pasighat", label: "Pasighat" },
    { value: "bomdila", label: "Bomdila" },
    { value: "tezu", label: "Tezu" },
  ],
  assam: [
    { value: "guwahati", label: "Guwahati" },
    { value: "dibrugarh", label: "Dibrugarh" },
    { value: "silchar", label: "Silchar" },
    { value: "tezpur", label: "Tezpur" },
    { value: "nagaon", label: "Nagaon" },
    { value: "jorhat", label: "Jorhat" },
  ],
  bihar: [
    { value: "patna", label: "Patna" },
    { value: "gaya", label: "Gaya" },
    { value: "bhagalpur", label: "Bhagalpur" },
    { value: "darbhanga", label: "Darbhanga" },
    { value: "muzzafarpur", label: "Muzaffarpur" },
    { value: "purnea", label: "Purnea" },
  ],
  chhattisgarh: [
    { value: "raipur", label: "Raipur" },
    { value: "bilaspur", label: "Bilaspur" },
    { value: "korba", label: "Korba" },
    { value: "durg", label: "Durg" },
    { value: "raigarh", label: "Raigarh" },
  ],
  delhi: [
    { value: "new-delhi", label: "New Delhi" },
    { value: "north-delhi", label: "North Delhi" },
    { value: "south-delhi", label: "South Delhi" },
    { value: "east-delhi", label: "East Delhi" },
    { value: "west-delhi", label: "West Delhi" },
  ],
  goa: [
    { value: "panaji", label: "Panaji" },
    { value: "margao", label: "Margao" },
    { value: "vasco-da-gama", label: "Vasco da Gama" },
    { value: "ponda", label: "Ponda" },
    { value: "mapusa", label: "Mapusa" },
  ],
  gujarat: [
    { value: "ahmedabad", label: "Ahmedabad" },
    { value: "surat", label: "Surat" },
    { value: "vadodara", label: "Vadodara" },
    { value: "rajkot", label: "Rajkot" },
    { value: "nadiad", label: "Nadiad" },
    { value: "bhavnagar", label: "Bhavnagar" },
  ],
  haryana: [
    { value: "faridabad", label: "Faridabad" },
    { value: "gurgaon", label: "Gurgaon" },
    { value: "panipat", label: "Panipat" },
    { value: "ambala", label: "Ambala" },
    { value: "karnal", label: "Karnal" },
  ],
  "himachal-pradesh": [
    { value: "shimla", label: "Shimla" },
    { value: "manali", label: "Manali" },
    { value: "dharmshala", label: "Dharamshala" },
    { value: "solan", label: "Solan" },
    { value: "kullu", label: "Kullu" },
  ],
  jharkhand: [
    { value: "ranchi", label: "Ranchi" },
    { value: "jamshedpur", label: "Jamshedpur" },
    { value: "dhanbad", label: "Dhanbad" },
    { value: "deoghar", label: "Deoghar" },
    { value: "bokaro", label: "Bokaro" },
  ],
  karnataka: [
    { value: "bengaluru", label: "Bengaluru" },
    { value: "mysuru", label: "Mysuru" },
    { value: "hubli", label: "Hubli" },
    { value: "mangaluru", label: "Mangaluru" },
    { value: "bellary", label: "Bellary" },
    { value: "davangere", label: "Davangere" },
  ],
  kerala: [
    { value: "thiruvananthapuram", label: "Thiruvananthapuram" },
    { value: "kochi", label: "Kochi" },
    { value: "kollam", label: "Kollam" },
    { value: "calicut", label: "Calicut" },
    { value: "malappuram", label: "Malappuram" },
  ],
  ladakh: [
    { value: "leh", label: "Leh" },
    { value: "kargil", label: "Kargil" },
  ],
  maharashtra: [
    { value: "mumbai", label: "Mumbai" },
    { value: "pune", label: "Pune" },
    { value: "nashik", label: "Nashik" },
    { value: "nagpur", label: "Nagpur" },
    { value: "aurangabad", label: "Aurangabad" },
  ],
  manipur: [
    { value: "imphal", label: "Imphal" },
    { value: "churachandpur", label: "Churachandpur" },
    { value: "bishnupur", label: "Bishnupur" },
    { value: "thoubal", label: "Thoubal" },
    { value: "kakching", label: "Kakching" },
  ],
  meghalaya: [
    { value: "shillong", label: "Shillong" },
    { value: "tura", label: "Tura" },
    { value: "nongsang", label: "Nongsang" },
    { value: "jowai", label: "Jowai" },
    { value: "bholaganj", label: "Bholaganj" },
  ],
  mizoram: [
    { value: "aizawl", label: "Aizawl" },
    { value: "lunglei", label: "Lunglei" },
    { value: "kolasib", label: "Kolasib" },
    { value: "serchhip", label: "Serchhip" },
    { value: "mamit", label: "Mamit" },
  ],
  nagaland: [
    { value: "dimapur", label: "Dimapur" },
    { value: "kohima", label: "Kohima" },
    { value: "mokokchung", label: "Mokokchung" },
    { value: "tuensang", label: "Tuensang" },
    { value: "wokha", label: "Wokha" },
  ],
  odisha: [
    { value: "bhubaneswar", label: "Bhubaneswar" },
    { value: "cuttack", label: "Cuttack" },
    { value: "rourkela", label: "Rourkela" },
    { value: "berhampur", label: "Berhampur" },
    { value: "sambalpur", label: "Sambalpur" },
  ],
  punjab: [
    { value: "chandigarh", label: "Chandigarh" },
    { value: "ludhiana", label: "Ludhiana" },
    { value: "amritsar", label: "Amritsar" },
    { value: "patiala", label: "Patiala" },
    { value: "jalandhar", label: "Jalandhar" },
  ],
  rajasthan: [
    { value: "jaipur", label: "Jaipur" },
    { value: "udaipur", label: "Udaipur" },
    { value: "jodhpur", label: "Jodhpur" },
    { value: "ajmer", label: "Ajmer" },
    { value: "bikaner", label: "Bikaner" },
  ],
  sikkim: [
    { value: "gangtok", label: "Gangtok" },
    { value: "namchi", label: "Namchi" },
    { value: "pelling", label: "Pelling" },
    { value: "mangan", label: "Mangan" },
  ],
  "tamil-nadu": [
    { value: "chennai", label: "Chennai" },
    { value: "coimbatore", label: "Coimbatore" },
    { value: "madurai", label: "Madurai" },
    { value: "salem", label: "Salem" },
    { value: "tiruchirappalli", label: "Tiruchirappalli" },
  ],
  telangana: [
    { value: "hyderabad", label: "Hyderabad" },
    { value: "warangal", label: "Warangal" },
    { value: "karimnagar", label: "Karimnagar" },
    { value: "nizamabad", label: "Nizamabad" },
    { value: "khammam", label: "Khammam" },
  ],
  tripura: [
    { value: "agartala", label: "Agartala" },
    { value: "ambassa", label: "Ambassa" },
    { value: "belonia", label: "Belonia" },
    { value: "sabroom", label: "Sabroom" },
  ],
  "uttar-pradesh": [
    { value: "lucknow", label: "Lucknow" },
    { value: "kanpur", label: "Kanpur" },
    { value: "varanasi", label: "Varanasi" },
    { value: "agra", label: "Agra" },
    { value: "meerut", label: "Meerut" },
  ],
  uttarakhand: [
    { value: "dehradun", label: "Dehradun" },
    { value: "haridwar", label: "Haridwar" },
    { value: "nainital", label: "Nainital" },
    { value: "roorkee", label: "Roorkee" },
    { value: "rishikesh", label: "Rishikesh" },
  ],
  "west-bengal": [
    { value: "kolkata", label: "Kolkata" },
    { value: "howrah", label: "Howrah" },
    { value: "durgapur", label: "Durgapur" },
    { value: "asansol", label: "Asansol" },
    { value: "siliguri", label: "Siliguri" },
  ],
  puducherry: [
    { value: "puducherry", label: "Puducherry" },
    { value: "karaikal", label: "Karaikal" },
    { value: "yanam", label: "Yanam" },
    { value: "mahe", label: "Mahe" },
  ],
};

export const contactFormFields = [
  {
    id: "mobileNumber",
    label: "Mobile Number",
    type: "text",
    required: true,
    defaultValue: "9912345678",
    validation: {
      required: "Mobile number is required",
      pattern: {
        value: /^[6-9]\d{9}$/,
        message: "Please enter a valid 10-digit Indian mobile number",
      },
    },
  },
  {
    id: "email",
    label: "Email address",
    type: "email",
    required: true,
    defaultValue: "user@gmail.com",
    validation: {
      required: "Email address is required",
      pattern: {
        value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
        message: "Please enter a valid email address",
      },
    },
  },
  {
    id: "state",
    label: "State",
    type: "select",
    required: true,
    defaultValue: "andhra-pradesh",
    validation: {
      required: "State is required",
    },
  },
  {
    id: "city",
    label: "City",
    type: "select",
    required: true,
    defaultValue: "",
    validation: {
      required: "City is required",
    },
  },
];
