export const examsList = [
  {
    id: 1,
    title: "UPSC CDS 2026",
    path: "upsc-cds",
    applicationDate: "2024-12-15",
    examDate: "2026-02-20",
    resultDate: "2026-04-15",
    links: [
      "OVERVIEW",
      "APPLICATION FORM",
      "ELIGIBILITY",
      "EXAM PATTERN",
      "HOW TO PREPARE",
    ],
    streams: ["Defence", "Engineering"],
    degree: ["B.Tech", "B.Sc"],
    level: "UG",
    mode: "Offline",
  },
  {
    id: 2,
    title: "CPNET UP 2025",
    path: "cpnet-up",
    applicationDate: "2024-08-10",
    examDate: "2025-01-15",
    resultDate: "2025-02-28",
    links: [
      "OVERVIEW",
      "ADMIT CARD",
      "HOW TO PREPARE",
      "EXAM PATTERN",
      "SYLLABUS",
    ],
    streams: ["Management", "Commerce"],
    degree: ["MBA", "BBA"],
    level: "PG",
    mode: "Online",
  },
  {
    id: 3,
    title: "JEE Main 2026",
    path: "jee-main",
    applicationDate: "2025-01-10",
    examDate: "2026-01-24",
    resultDate: "2026-02-15",
    links: ["OVERVIEW", "APPLICATION FORM", "SYLLABUS", "EXAM PATTERN"],
    streams: ["Engineering"],
    degree: ["B.Tech"],
    level: "UG",
    mode: "Online",
  },
  {
    id: 4,
    title: "NEET UG 2026",
    path: "neet-ug",
    applicationDate: "2025-02-15",
    examDate: "2026-05-07",
    resultDate: "2026-06-30",
    links: ["OVERVIEW", "APPLICATION FORM", "SYLLABUS", "EXAM PATTERN"],
    streams: ["Medical"],
    degree: ["MBBS", "BDS"],
    level: "UG",
    mode: "Offline",
  },
  {
    id: 5,
    title: "CAT 2026",
    path: "cat",
    applicationDate: "2025-08-01",
    examDate: "2026-11-27",
    resultDate: "2026-12-20",
    links: ["OVERVIEW", "APPLICATION FORM", "SYLLABUS", "EXAM PATTERN"],
    streams: ["Management"],
    degree: ["MBA"],
    level: "PG",
    mode: "Online",
  },
  {
    id: 6,
    title: "GATE 2026",
    path: "gate",
    applicationDate: "2025-09-15",
    examDate: "2026-02-05",
    resultDate: "2026-03-16",
    links: ["OVERVIEW", "APPLICATION FORM", "SYLLABUS", "EXAM PATTERN"],
    streams: ["Engineering", "Science"],
    degree: ["M.Tech", "Ph.D."],
    level: "PG",
    mode: "Online",
  },
  {
    id: 7,
    title: "CLAT 2026",
    path: "clat",
    applicationDate: "2025-01-20",
    examDate: "2026-05-08",
    resultDate: "2026-06-15",
    links: ["OVERVIEW", "APPLICATION FORM", "SYLLABUS", "EXAM PATTERN"],
    streams: ["Law"],
    degree: ["BA LLB", "LLM"],
    level: "UG/PG",
    mode: "Offline",
  },
  {
    id: 8,
    title: "IBPS PO 2026",
    path: "ibps-po",
    applicationDate: "2025-06-01",
    examDate: "2026-10-10",
    resultDate: "2026-11-20",
    links: ["OVERVIEW", "APPLICATION FORM", "SYLLABUS", "EXAM PATTERN"],
    streams: ["Banking", "Finance"],
    degree: ["B.Com", "MBA"],
    level: "UG/PG",
    mode: "Online",
  },
  {
    id: 9,
    title: "SSC CGL 2026",
    path: "ssc-cgl",
    applicationDate: "2025-07-15",
    examDate: "2026-08-20",
    resultDate: "2026-09-30",
    links: ["OVERVIEW", "APPLICATION FORM", "SYLLABUS", "EXAM PATTERN"],
    streams: ["General"],
    degree: ["B.A.", "B.Com"],
    level: "UG",
    mode: "Online",
  },
  {
    id: 10,
    title: "UPSC Civil Services 2026",
    path: "upsc-civil-services",
    applicationDate: "2025-03-15",
    examDate: "2026-06-12",
    resultDate: "2026-08-20",
    links: [
      "OVERVIEW",
      "APPLICATION FORM",
      "ELIGIBILITY",
      "EXAM PATTERN",
      "HOW TO PREPARE",
    ],
    streams: ["General"],
    degree: ["B.A.", "B.Com"],
    level: "UG",
    mode: "Offline",
  },
];

export const sortOptions = [
  { value: "application_date", label: "Application Date" },
  { value: "exam_date", label: "Exam Date" },
  { value: "result_date", label: "Result Date" },
];
